# vpath socket.hh ../util
# vpath socket.cc ../util

target: webget.cc ../util/socket.cc ../util/address.cc ../util/file_descriptor.cc
	g++ webget.cc ../util/socket.cc ../util/address.cc ../util/file_descriptor.cc -o webget -std=c++20



